const KEY="jaimie-day-v1";let state={date:new Date(),data:load()},mode="quest";const $=s=>document.querySelector(s);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.data))}
function key(d){return d.toISOString().slice(0,10)}
function current(){let k=key(state.date);if(!state.data[k])state.data[k]={schedule:[],quests:[]};return state.data[k]}
function rem(){if(!state.data.reminders)state.data.reminders=[];return state.data.reminders}
function esc(s){return String(s??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}
function render(){let d=state.date,x=current();$("#date").textContent=d.toLocaleDateString(undefined,{month:"short",day:"2-digit",year:"numeric"}).toUpperCase();$("#weekday").textContent=d.toLocaleDateString(undefined,{weekday:"long"});
$("#schedule").innerHTML=x.schedule.length?x.schedule.map((a,i)=>`<div class="entry"><div class="time">${a.time||"--:--"}</div><div><div class="title">${esc(a.title)}</div>${a.note?`<div class="note">${esc(a.note)}</div>`:""}</div><button class="mini" data-del="schedule,${i}">×</button></div>`).join(""):`<div class="note">NO SCHEDULE ENTRIES</div>`;
$("#quests").innerHTML=x.quests.length?x.quests.map((a,i)=>`<div class="task"><button class="check ${a.done?"done":""}" data-check="${i}">${a.done?"✓":""}</button><div><div class="title ${a.done?"doneText":""}">${esc(a.title)}</div>${a.note?`<div class="note">${esc(a.note)}</div>`:""}</div><div><button class="mini" data-post="${i}">→</button><button class="mini" data-del="quests,${i}">×</button></div></div>`).join(""):`<div class="note">NO ACTIVE OBJECTIVES</div>`;
let done=x.quests.filter(a=>a.done).length,p=x.quests.length?Math.round(done/x.quests.length*100):0;$("#percent").textContent=p+"%";$("#bar").style.width=p+"%";
let r=rem();$("#reminders").innerHTML=r.length?r.map((a,i)=>`<div class="task"><button class="check ${a.done?"done":""}" data-rem="${i}">${a.done?"✓":""}</button><div><div class="title ${a.done?"doneText":""}">${esc(a.title)}</div>${a.note?`<div class="note">${esc(a.note)}</div>`:""}</div><button class="mini" data-rdel="${i}">×</button></div>`).join(""):`<div class="note">NO ACTIVE REMINDERS</div>`}
function open(type){mode=type;$("#modalTitle").textContent=type==="schedule"?"Add Schedule Entry":type==="quest"?"Add Main Quest":"Add Persistent Reminder";$("#modalType").textContent=type==="schedule"?"01 / TIME GRID":type==="quest"?"02 / ACTIVE OBJECTIVES":"03 / PERSISTENT";$("#timeRow").style.display=type==="schedule"?"block":"none";$("#title").value="";$("#note").value="";$("#time").value="";$("#modal").hidden=false;$("#title").focus()}
$("#prevDay").onclick=()=>{state.date.setDate(state.date.getDate()-1);render()};$("#nextDay").onclick=()=>{state.date.setDate(state.date.getDate()+1);render()};$("#today").onclick=()=>{state.date=new Date();render()};
$("#addSchedule").onclick=()=>open("schedule");$("#addQuest").onclick=()=>open("quest");$("#addReminder").onclick=()=>open("reminder");$("#close").onclick=()=>$("#modal").hidden=true;
$("#form").onsubmit=e=>{e.preventDefault();let a={title:$("#title").value.trim(),note:$("#note").value.trim(),time:$("#time").value,done:false};if(!a.title)return;if(mode==="schedule")current().schedule.push(a);else if(mode==="quest")current().quests.push(a);else rem().push(a);save();render();$("#modal").hidden=true};
document.addEventListener("click",e=>{let c=e.target.closest("[data-check]");if(c){current().quests[+c.dataset.check].done=!current().quests[+c.dataset.check].done;save();render()}let r=e.target.closest("[data-rem]");if(r){rem()[+r.dataset.rem].done=!rem()[+r.dataset.rem].done;save();render()}let d=e.target.closest("[data-del]");if(d){let [t,i]=d.dataset.del.split(",");current()[t].splice(+i,1);save();render()}let rd=e.target.closest("[data-rdel]");if(rd){rem().splice(+rd.dataset.rdel,1);save();render()}let p=e.target.closest("[data-post]");if(p){let item=current().quests.splice(+p.dataset.post,1)[0],n=new Date(state.date);n.setDate(n.getDate()+1);let k=key(n);if(!state.data[k])state.data[k]={schedule:[],quests:[]};state.data[k].quests.push(item);save();render()}});
document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#modal").hidden=true});render();