const KEY="jetbrains-workout-tracker-v1";
const fresh=()=>({selectedDate:key(new Date()),days:{},workouts:[]});
let state=(()=>{try{return {...fresh(),...(JSON.parse(localStorage.getItem(KEY))||{})}}catch{return fresh()}})();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function key(d){d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function currentDate(){return new Date(state.selectedDate+"T12:00:00")}
function day(){return state.days[state.selectedDate]||(state.days[state.selectedDate]={rest:false,exercises:[]})}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()}
function fmt(d){return new Intl.DateTimeFormat(undefined,{weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(d)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

function render(){
 const d=day(), date=currentDate(), today=state.selectedDate===key(new Date());
 document.querySelector("#app").innerHTML=`<div class="app"><header class="topbar"><div class="brand"><div class="logo"></div> Workout Tracker</div><nav class="nav"><button class="active">Workout</button></nav></header><main class="main">
 <div class="day-header"><button class="day-nav" data-a="prev">←</button><div class="date-heading"><div class="eyebrow">Workout / Daily Log</div><h1>${today?"Today's Workout":fmt(date)}</h1><div class="date-label">${fmt(date)}</div>${!today?'<button class="today-btn" data-a="today">Jump to today</button>':""}</div><button class="day-nav" data-a="next">→</button></div>
 <div class="layout"><section class="workout-panel"><div class="panel-header"><div><div class="panel-title">${d.rest?"Rest Day":"Workout Log"}</div><div class="panel-subtitle">${d.rest?"Recovery day — no exercises scheduled.":`${d.exercises.length} exercise${d.exercises.length===1?"":"s"} logged`}</div></div><div class="actions"><button class="secondary" data-a="rest">${d.rest?"Undo Rest Day":"Mark Rest Day"}</button><button class="secondary" data-a="pick">Select Workout</button><button class="primary" data-a="add">+ Add Exercise</button></div></div>
 ${d.rest?`<div class="empty"><div><div class="empty-icon">◌</div><strong>Recovery mode</strong><p>This day is marked as a rest day.</p></div></div>`:`<div class="exercise-list">${d.exercises.length?d.exercises.map(exercise).join(""):`<div class="empty"><div><div class="empty-icon">＋</div><strong>No exercises yet</strong><p>Select a pre-made workout or add exercises individually.</p></div></div>`}</div>`}
 </section><aside class="side-panel"><div class="side-title">Saved Workouts</div><div class="side-copy">Create reusable workouts with full control over exercises, sets and reps.</div><div class="workout-library">${state.workouts.length?state.workouts.map(w=>`<div class="library-item"><div><strong>${esc(w.name)}</strong><span>${w.exercises.length} exercises</span></div><button class="mini-btn" data-use="${w.id}">Use</button></div>`).join(""):`<div class="side-copy" style="padding:12px 2px">No saved workouts yet.</div>`}</div><div style="margin-top:14px"><button class="secondary" data-a="manage">Manage / Create Workouts</button></div></aside></div></main></div>`;
 bind();
}
function exercise(e){return `<article class="exercise"><div class="exercise-main"><div><div class="exercise-name">${esc(e.name)}</div><div class="exercise-meta">${e.sets.length} sets planned · target ${e.targetReps||"—"} reps</div><div class="set-counter">${e.sets.map((s,i)=>`<div class="set-chip ${s.done?"done":""}"><small>SET ${i+1}</small>${s.reps} reps</div>`).join("")}<button class="counter-btn" data-setadd="${e.id}">+</button></div></div><div class="exercise-actions"><button class="mini-btn" data-done="${e.id}">1 Set Done</button><button class="mini-btn" data-undo="${e.id}">Undo 1</button><button class="danger-btn" data-remove="${e.id}">×</button></div></div><div class="set-row"><span class="set-label">Reps:</span>${e.sets.map((s,i)=>`<input class="rep-input" type="number" min="0" value="${s.reps}" data-reps="${e.id}" data-i="${i}">`).join("")}</div></article>`}

function shift(n){let d=currentDate();d.setDate(d.getDate()+n);state.selectedDate=key(d);save();render()}
function bind(){
 document.querySelector("[data-a=prev]").onclick=()=>shift(-1);document.querySelector("[data-a=next]").onclick=()=>shift(1);
 document.querySelector("[data-a=today]")?.addEventListener("click",()=>{state.selectedDate=key(new Date());save();render()});
 document.querySelector("[data-a=rest]").onclick=()=>{day().rest=!day().rest;save();render()};
 document.querySelector("[data-a=add]").onclick=addModal;document.querySelector("[data-a=pick]").onclick=pickModal;document.querySelector("[data-a=manage]").onclick=manageModal;
 document.querySelectorAll("[data-use]").forEach(b=>b.onclick=()=>apply(state.workouts.find(w=>w.id===b.dataset.use)));
 document.querySelectorAll("[data-done]").forEach(b=>b.onclick=()=>setDone(b.dataset.done,true));document.querySelectorAll("[data-undo]").forEach(b=>b.onclick=()=>setDone(b.dataset.undo,false));
 document.querySelectorAll("[data-setadd]").forEach(b=>b.onclick=()=>{let e=day().exercises.find(x=>x.id===b.dataset.setadd);e.sets.push({reps:+e.targetReps||0,done:false});save();render()});
 document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{day().exercises=day().exercises.filter(e=>e.id!==b.dataset.remove);save();render()});
 document.querySelectorAll("[data-reps]").forEach(i=>i.onchange=()=>{let e=day().exercises.find(x=>x.id===i.dataset.reps);e.sets[+i.dataset.i].reps=+i.value||0;save()});
}
function setDone(id,done){let e=day().exercises.find(x=>x.id===id);let s=done?e.sets.find(x=>!x.done):[...e.sets].reverse().find(x=>x.done);if(s)s.done=done;save();render()}
function modal(html){let x=document.createElement("div");x.className="modal-backdrop";x.id="modal";x.innerHTML=`<div class="modal">${html}</div>`;document.body.appendChild(x);document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>x.remove())}
function addModal(){modal(`<div class="modal-header"><div class="modal-title">Add Individual Exercise</div><button class="close" data-close>×</button></div><form class="modal-body" id="ef"><div class="field"><label>Exercise name</label><input id="en" placeholder="e.g. Pull-ups" required></div><div class="field"><label>Number of sets</label><input id="es" type="number" min="1" value="3" required></div><div class="field"><label>Target reps per set</label><input id="er" type="number" min="0" value="10" required></div><div class="modal-footer"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Add Exercise</button></div></form>`);document.querySelector("#ef").onsubmit=e=>{e.preventDefault();let n=en.value.trim(),s=+es.value,r=+er.value;if(!n||s<1)return;day().exercises.push({id:uid(),name:n,targetReps:r,sets:Array.from({length:s},()=>({reps:r,done:false}))});save();document.querySelector("#modal").remove();render()}}
function pickModal(){modal(`<div class="modal-header"><div class="modal-title">Select Pre-made Workout</div><button class="close" data-close>×</button></div><div class="modal-body">${state.workouts.length?state.workouts.map(w=>`<div class="library-item" style="margin-bottom:8px"><div><strong>${esc(w.name)}</strong><span>${w.exercises.map(e=>`${esc(e.name)} ${e.sets}×${e.reps}`).join(" · ")}</span></div><button class="primary" data-pick="${w.id}">Use</button></div>`).join(""):`<div class="empty" style="min-height:180px">No workouts created yet.</div>`}</div><div class="modal-footer"><button class="secondary" data-manage>Manage / Create</button><button class="secondary" data-close>Close</button></div>`);
 document.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>{apply(state.workouts.find(w=>w.id===b.dataset.pick));document.querySelector("#modal").remove()});document.querySelector("[data-manage]")?.addEventListener("click",manageModal)}
function manageModal(){modal(`<div class="modal-header"><div class="modal-title">Workout Library</div><button class="close" data-close>×</button></div><div class="modal-body"><div class="side-copy" style="margin-bottom:15px">Build reusable workouts with unlimited exercises and individual set/rep targets.</div><form id="wf"><div class="field"><label>Workout name</label><input id="wn" placeholder="e.g. Push Day" required></div><label>Exercises</label><div id="builder" class="builder"></div><button type="button" class="secondary" id="badd">+ Add Exercise</button><div class="modal-footer"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save Workout</button></div></form><hr style="border-color:#3b3d44;border-width:1px 0 0;margin:18px 0">${state.workouts.map(w=>`<div class="library-item" style="margin-bottom:7px"><div><strong>${esc(w.name)}</strong><span>${w.exercises.length} exercises</span></div><button type="button" class="danger-btn" data-delw="${w.id}">Delete</button></div>`).join("")}</div>`);
 addRow();document.querySelector("#badd").onclick=addRow;document.querySelector("#wf").onsubmit=e=>{e.preventDefault();let rows=[...document.querySelectorAll(".builder-row")],ex=rows.map(r=>({name:r.querySelector(".bn").value.trim(),sets:+r.querySelector(".bs").value,reps:+r.querySelector(".br").value})).filter(x=>x.name&&x.sets>0);if(!wn.value.trim()||!ex.length)return;state.workouts.push({id:uid(),name:wn.value.trim(),exercises:ex});save();manageModal()};document.querySelectorAll("[data-delw]").forEach(b=>b.onclick=()=>{state.workouts=state.workouts.filter(w=>w.id!==b.dataset.delw);save();manageModal()})}
function addRow(){let b=document.querySelector("#builder"),r=document.createElement("div");r.className="builder-row";r.innerHTML=`<input class="bn" placeholder="Exercise" required><input class="bs" type="number" min="1" value="3" required><input class="br" type="number" min="0" value="10" required><button type="button" class="remove-row">×</button>`;r.querySelector(".remove-row").onclick=()=>r.remove();b.appendChild(r)}
function apply(w){if(!w)return;w.exercises.forEach(e=>day().exercises.push({id:uid(),name:e.name,targetReps:e.reps,sets:Array.from({length:e.sets},()=>({reps:e.reps,done:false}))}));save();render()}
render();